### ISSUE TITLE
wso2is pod failing with Parameter KUBERNETES_API_SERVER not found error

### ISSUE THREAD

**Issue by Srimrao02** [wso2/kubernetes-is#131]
**Description:**
While the wso2is pod is coming up, we are ending up with issues that KUBERNETES parametrs are not found

> [2019-07-10 07:40:56,879]  INFO {org.wso2.carbon.membership.scheme.kubernetes.resolver.ApiBasedPodIpResolver} -  Parameter KUBERNETES_API_SERVER not found, checking KUBERNETES_SERVICE_HOST & KUBERNETES_SERVICE_PORT_HTTPS
> [2019-07-10 07:40:56,879]  INFO {org.wso2.carbon.membership.scheme.kubernetes.resolver.ApiBasedPodIpResolver} -  Kubernetes clustering configuration: [api-server] https://172.30.0.1:443  [namespace] wso2 [services] wso2is-service [skip-master-ssl-verification] true
> [2019-07-10 07:40:57,010] ERROR {org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme} -  Kubernetes membership initialization failed

> Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://172.30.0.1:443/api/v1/namespaces/wso2/endpoints/wso2is-service 
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.wso2.carbon.membership.scheme.kubernetes.api.KubernetesApiEndpoint.read(KubernetesApiEndpoint.java:45)
> 	at org.wso2.carbon.membership.scheme.kubernetes.resolver.ApiBasedPodIpResolver.connectAndRead(ApiBasedPodIpResolver.java:223)
> 	... 81 more

**Suggested Labels:**

**Affected Product Version:** 
wso2/wso2is:5.8.0

**Steps to reproduce:**
Deploy the wso2is using helm patter https://github.com/wso2/kubernetes-is/blob/master/advanced/helm/is/README.md.
Nginx & Mysql comes up.
Wso2is fails

**Comment by Srimrao02** [comment]
[wso2is-deployment-cb7574bd9-4f4hm.log](https://github.com/wso2/kubernetes-is/files/3376335/wso2is-deployment-cb7574bd9-4f4hm.log)

Complete POD startup log.

**Comment by Srimrao02** [comment]
This stands fixed.
On the helm charts under identity server resource we have a config file  “confs/axis2/axis2.xml”, this config file refers to a parameter “<parameter name="KUBERNETES_NAMESPACE">wso2</parameter>”.
So the name space which we are passing on values.yaml and on this parameter should be same.
